var bs_data=[
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":41086,
        "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":2794,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF2",
                "start":2263,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":261.0,
                        "code":"PF00155",
                        "end":385,
                        "start":30
                    }
                ],
                "end":4000,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF3",
                "start":2815,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":50.4,
                        "code":"PF01336",
                        "end":95,
                        "start":16
                    },
                    {
                        "bitscore":283.4,
                        "code":"PF00152",
                        "end":425,
                        "start":109
                    }
                ],
                "end":5315,
                "id":"asnS",
                "start":4022,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":88.7,
                        "code":"PF07261",
                        "end":199,
                        "start":126
                    }
                ],
                "end":6085,
                "id":"dnaD",
                "start":5389,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":84.3,
                        "code":"PF00730",
                        "end":171,
                        "start":35
                    }
                ],
                "end":6761,
                "id":"nth",
                "start":6098,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":33.1,
                        "code":"PF00041",
                        "end":763,
                        "start":684
                    },
                    {
                        "bitscore":130.8,
                        "code":"PF00905",
                        "end":621,
                        "start":346
                    },
                    {
                        "bitscore":204.3,
                        "code":"PF00912",
                        "end":255,
                        "start":77
                    }
                ],
                "end":9465,
                "id":"ponA",
                "start":6801,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":219.6,
                        "code":"PF03838",
                        "end":190,
                        "start":25
                    }
                ],
                "end":10066,
                "id":"recU",
                "start":9481,
                "strand":-1
            },
            {
                "domains":[],
                "end":10837,
                "id":"racA",
                "start":10570,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":94.2,
                        "code":"PF08807",
                        "end":115,
                        "start":7
                    }
                ],
                "end":11266,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF10",
                "start":10894,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":535.1,
                        "code":"PF00873",
                        "end":1012,
                        "start":1
                    }
                ],
                "end":14344,
                "id":"swrC_1",
                "start":11278,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":59.8,
                        "code":"PF00383",
                        "end":105,
                        "start":1
                    }
                ],
                "end":14924,
                "id":"cdd",
                "start":14516,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":221.5,
                        "code":"PF06908",
                        "end":170,
                        "start":4
                    }
                ],
                "end":15568,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF13",
                "start":15004,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":52.7,
                        "code":"PF05103",
                        "end":71,
                        "start":8
                    }
                ],
                "end":16001,
                "id":"gpsB",
                "start":15680,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":50.5,
                        "code":"PF02926",
                        "end":157,
                        "start":13
                    },
                    {
                        "bitscore":207.0,
                        "code":"PF01170",
                        "end":371,
                        "start":165
                    }
                ],
                "end":17731,
                "id":"rlmL",
                "start":16597,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":614.8,
                        "code":"PF02074",
                        "end":491,
                        "start":8
                    }
                ],
                "end":19242,
                "id":"ypwA",
                "start":17748,
                "strand":1
            },
            {
                "domains":[],
                "end":19807,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF17",
                "start":19408,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":88.8,
                        "code":"PF00195",
                        "end":208,
                        "start":2
                    }
                ],
                "end":21086,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF18",
                "start":20000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":94.6,
                        "code":"PF04140",
                        "end":162,
                        "start":70
                    }
                ],
                "end":21582,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF19",
                "start":21087,
                "strand":1
            },
            {
                "domains":[],
                "end":22014,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF20",
                "start":21711,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":46.6,
                        "code":"PF00075",
                        "end":124,
                        "start":1
                    }
                ],
                "end":22405,
                "id":"rnhA",
                "start":22021,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":180.7,
                        "code":"PF02592",
                        "end":218,
                        "start":57
                    }
                ],
                "end":23098,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF22",
                "start":22423,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":883.3,
                        "code":"PF01268",
                        "end":556,
                        "start":2
                    }
                ],
                "end":24949,
                "id":"fhs",
                "start":23278,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":202.4,
                        "code":"PF01904",
                        "end":266,
                        "start":17
                    }
                ],
                "end":25860,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF24",
                "start":25005,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":36.4,
                        "code":"PF01966",
                        "end":125,
                        "start":26
                    }
                ],
                "end":26496,
                "id":"yedJ",
                "start":25869,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":403.1,
                        "code":"PF00303",
                        "end":318,
                        "start":5
                    }
                ],
                "end":27442,
                "id":"thyA",
                "start":26485,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":214.3,
                        "code":"PF00186",
                        "end":161,
                        "start":1
                    }
                ],
                "end":27957,
                "id":"dfrA",
                "start":27462,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":113.0,
                        "code":"PF12804",
                        "end":161,
                        "start":8
                    }
                ],
                "end":28541,
                "id":"mobA",
                "start":27953,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":72.2,
                        "code":"PF02416",
                        "end":71,
                        "start":5
                    }
                ],
                "end":28875,
                "id":"tatA",
                "start":28656,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":65.7,
                        "code":"PF02416",
                        "end":58,
                        "start":5
                    }
                ],
                "end":29072,
                "id":"tatAd_1",
                "start":28889,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":172.6,
                        "code":"PF00902",
                        "end":221,
                        "start":17
                    }
                ],
                "end":29913,
                "id":"tatC1_1",
                "start":29145,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":89.8,
                        "code":"PF06855",
                        "end":69,
                        "start":3
                    }
                ],
                "end":30216,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF32",
                "start":29997,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":58.9,
                        "code":"PF00149",
                        "end":219,
                        "start":1
                    },
                    {
                        "bitscore":50.4,
                        "code":"PF12320",
                        "end":358,
                        "start":267
                    }
                ],
                "end":31474,
                "id":"sbcD",
                "start":30319,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":64.1,
                        "code":"PF13476",
                        "end":378,
                        "start":5
                    },
                    {
                        "bitscore":50.0,
                        "code":"PF13558",
                        "end":997,
                        "start":914
                    }
                ],
                "end":34592,
                "id":"sbcC",
                "start":31475,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":101.3,
                        "code":"PF10763",
                        "end":82,
                        "start":1
                    }
                ],
                "end":34863,
                "id":"ytmB",
                "start":34614,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":92.1,
                        "code":"PF03167",
                        "end":213,
                        "start":50
                    }
                ],
                "end":35636,
                "id":"ung",
                "start":34961,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":72.7,
                        "code":"PF14181",
                        "end":175,
                        "start":35
                    }
                ],
                "end":36234,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF37",
                "start":35706,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":198.0,
                        "code":"PF01625",
                        "end":159,
                        "start":7
                    },
                    {
                        "bitscore":166.1,
                        "code":"PF01641",
                        "end":302,
                        "start":182
                    }
                ],
                "end":37282,
                "id":"msrB_2",
                "start":36319,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":31.8,
                        "code":"PF00440",
                        "end":58,
                        "start":12
                    }
                ],
                "end":38465,
                "id":"betI_1",
                "start":37886,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":38.8,
                        "code":"PF00583",
                        "end":164,
                        "start":31
                    }
                ],
                "end":39141,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF40",
                "start":38469,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":44.9,
                        "code":"PF01738",
                        "end":200,
                        "start":59
                    }
                ],
                "end":39918,
                "id":"mhqD",
                "start":39306,
                "strand":1
            },
            {
                "domains":[],
                "end":40174,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF42",
                "start":39970,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":94.6,
                        "code":"PF00300",
                        "end":179,
                        "start":4
                    }
                ],
                "end":40868,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region001_ORF43",
                "start":40322,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":41086,
        "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[],
                "end":2794,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF2",
                "start":2263,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":261.0,
                        "code":"PF00155",
                        "end":385,
                        "start":30
                    }
                ],
                "end":4000,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF3",
                "start":2815,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":50.4,
                        "code":"PF01336",
                        "end":95,
                        "start":16
                    },
                    {
                        "bitscore":283.4,
                        "code":"PF00152",
                        "end":425,
                        "start":109
                    }
                ],
                "end":5315,
                "id":"asnS",
                "start":4022,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":88.7,
                        "code":"PF07261",
                        "end":199,
                        "start":126
                    }
                ],
                "end":6085,
                "id":"dnaD",
                "start":5389,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":84.3,
                        "code":"PF00730",
                        "end":171,
                        "start":35
                    }
                ],
                "end":6761,
                "id":"nth",
                "start":6098,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":33.1,
                        "code":"PF00041",
                        "end":763,
                        "start":684
                    },
                    {
                        "bitscore":130.8,
                        "code":"PF00905",
                        "end":621,
                        "start":346
                    },
                    {
                        "bitscore":204.3,
                        "code":"PF00912",
                        "end":255,
                        "start":77
                    }
                ],
                "end":9465,
                "id":"ponA",
                "start":6801,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":219.6,
                        "code":"PF03838",
                        "end":190,
                        "start":25
                    }
                ],
                "end":10066,
                "id":"recU",
                "start":9481,
                "strand":-1
            },
            {
                "domains":[],
                "end":10837,
                "id":"racA",
                "start":10570,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":94.2,
                        "code":"PF08807",
                        "end":115,
                        "start":7
                    }
                ],
                "end":11266,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF10",
                "start":10894,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":535.1,
                        "code":"PF00873",
                        "end":1012,
                        "start":1
                    }
                ],
                "end":14344,
                "id":"swrC_1",
                "start":11278,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":59.8,
                        "code":"PF00383",
                        "end":105,
                        "start":1
                    }
                ],
                "end":14924,
                "id":"cdd",
                "start":14516,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":221.5,
                        "code":"PF06908",
                        "end":170,
                        "start":4
                    }
                ],
                "end":15568,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF13",
                "start":15004,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":52.7,
                        "code":"PF05103",
                        "end":71,
                        "start":8
                    }
                ],
                "end":16001,
                "id":"gpsB",
                "start":15680,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":50.5,
                        "code":"PF02926",
                        "end":157,
                        "start":13
                    },
                    {
                        "bitscore":207.0,
                        "code":"PF01170",
                        "end":371,
                        "start":165
                    }
                ],
                "end":17731,
                "id":"rlmL",
                "start":16597,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":614.8,
                        "code":"PF02074",
                        "end":491,
                        "start":8
                    }
                ],
                "end":19242,
                "id":"ypwA",
                "start":17748,
                "strand":1
            },
            {
                "domains":[],
                "end":19807,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF17",
                "start":19408,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":88.8,
                        "code":"PF00195",
                        "end":208,
                        "start":2
                    }
                ],
                "end":21086,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF18",
                "start":20000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":94.6,
                        "code":"PF04140",
                        "end":162,
                        "start":70
                    }
                ],
                "end":21582,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF19",
                "start":21087,
                "strand":1
            },
            {
                "domains":[],
                "end":22014,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF20",
                "start":21711,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":46.6,
                        "code":"PF00075",
                        "end":124,
                        "start":1
                    }
                ],
                "end":22405,
                "id":"rnhA",
                "start":22021,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":180.7,
                        "code":"PF02592",
                        "end":218,
                        "start":57
                    }
                ],
                "end":23098,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF22",
                "start":22423,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":883.3,
                        "code":"PF01268",
                        "end":556,
                        "start":2
                    }
                ],
                "end":24949,
                "id":"fhs",
                "start":23278,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":202.4,
                        "code":"PF01904",
                        "end":266,
                        "start":17
                    }
                ],
                "end":25860,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF24",
                "start":25005,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":36.4,
                        "code":"PF01966",
                        "end":125,
                        "start":26
                    }
                ],
                "end":26496,
                "id":"yedJ",
                "start":25869,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":403.1,
                        "code":"PF00303",
                        "end":318,
                        "start":5
                    }
                ],
                "end":27442,
                "id":"thyA",
                "start":26485,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":214.3,
                        "code":"PF00186",
                        "end":161,
                        "start":1
                    }
                ],
                "end":27957,
                "id":"dfrA",
                "start":27462,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":113.0,
                        "code":"PF12804",
                        "end":161,
                        "start":8
                    }
                ],
                "end":28541,
                "id":"mobA",
                "start":27953,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":72.2,
                        "code":"PF02416",
                        "end":71,
                        "start":5
                    }
                ],
                "end":28875,
                "id":"tatA",
                "start":28656,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":65.7,
                        "code":"PF02416",
                        "end":58,
                        "start":5
                    }
                ],
                "end":29072,
                "id":"tatAd_1",
                "start":28889,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":172.6,
                        "code":"PF00902",
                        "end":221,
                        "start":17
                    }
                ],
                "end":29913,
                "id":"tatC1_1",
                "start":29145,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":89.8,
                        "code":"PF06855",
                        "end":69,
                        "start":3
                    }
                ],
                "end":30216,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF32",
                "start":29997,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":58.9,
                        "code":"PF00149",
                        "end":219,
                        "start":1
                    },
                    {
                        "bitscore":50.4,
                        "code":"PF12320",
                        "end":358,
                        "start":267
                    }
                ],
                "end":31474,
                "id":"sbcD",
                "start":30319,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":64.1,
                        "code":"PF13476",
                        "end":378,
                        "start":5
                    },
                    {
                        "bitscore":50.0,
                        "code":"PF13558",
                        "end":997,
                        "start":914
                    }
                ],
                "end":34592,
                "id":"sbcC",
                "start":31475,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":101.3,
                        "code":"PF10763",
                        "end":82,
                        "start":1
                    }
                ],
                "end":34863,
                "id":"ytmB",
                "start":34614,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":92.1,
                        "code":"PF03167",
                        "end":213,
                        "start":50
                    }
                ],
                "end":35636,
                "id":"ung",
                "start":34961,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":72.7,
                        "code":"PF14181",
                        "end":175,
                        "start":35
                    }
                ],
                "end":36234,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF37",
                "start":35706,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":198.0,
                        "code":"PF01625",
                        "end":159,
                        "start":7
                    },
                    {
                        "bitscore":166.1,
                        "code":"PF01641",
                        "end":302,
                        "start":182
                    }
                ],
                "end":37282,
                "id":"msrB_2",
                "start":36319,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":31.8,
                        "code":"PF00440",
                        "end":58,
                        "start":12
                    }
                ],
                "end":38465,
                "id":"betI_1",
                "start":37886,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":38.8,
                        "code":"PF00583",
                        "end":164,
                        "start":31
                    }
                ],
                "end":39141,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF40",
                "start":38469,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":44.9,
                        "code":"PF01738",
                        "end":200,
                        "start":59
                    }
                ],
                "end":39918,
                "id":"mhqD",
                "start":39306,
                "strand":1
            },
            {
                "domains":[],
                "end":40174,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF42",
                "start":39970,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":94.6,
                        "code":"PF00300",
                        "end":179,
                        "start":4
                    }
                ],
                "end":40868,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region001_ORF43",
                "start":40322,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":41086,
        "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":29.0,
                        "code":"PF17881",
                        "end":97,
                        "start":53
                    }
                ],
                "end":2318,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF2",
                "start":1787,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":265.8,
                        "code":"PF00155",
                        "end":385,
                        "start":30
                    }
                ],
                "end":3543,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF3",
                "start":2340,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":48.7,
                        "code":"PF01336",
                        "end":95,
                        "start":16
                    },
                    {
                        "bitscore":280.1,
                        "code":"PF00152",
                        "end":425,
                        "start":109
                    }
                ],
                "end":4839,
                "id":"asnS",
                "start":3546,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":91.1,
                        "code":"PF07261",
                        "end":150,
                        "start":77
                    }
                ],
                "end":5735,
                "id":"dnaD",
                "start":5186,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":80.5,
                        "code":"PF00730",
                        "end":171,
                        "start":35
                    }
                ],
                "end":6417,
                "id":"nth",
                "start":5748,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.4,
                        "code":"PF00041",
                        "end":768,
                        "start":689
                    },
                    {
                        "bitscore":133.9,
                        "code":"PF00905",
                        "end":626,
                        "start":345
                    },
                    {
                        "bitscore":205.5,
                        "code":"PF00912",
                        "end":255,
                        "start":77
                    }
                ],
                "end":9138,
                "id":"ponA",
                "start":6456,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":228.6,
                        "code":"PF03838",
                        "end":190,
                        "start":25
                    }
                ],
                "end":9739,
                "id":"recU",
                "start":9154,
                "strand":-1
            },
            {
                "domains":[],
                "end":10508,
                "id":"racA",
                "start":10241,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":97.3,
                        "code":"PF08807",
                        "end":115,
                        "start":7
                    }
                ],
                "end":10934,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF10",
                "start":10562,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":225.9,
                        "code":"PF00873",
                        "end":519,
                        "start":3
                    }
                ],
                "end":12727,
                "id":"mdtB",
                "start":11152,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":287.4,
                        "code":"PF00873",
                        "end":502,
                        "start":1
                    }
                ],
                "end":14207,
                "id":"ttgE",
                "start":12698,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":60.9,
                        "code":"PF00383",
                        "end":104,
                        "start":1
                    }
                ],
                "end":14774,
                "id":"cdd",
                "start":14378,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":216.3,
                        "code":"PF06908",
                        "end":170,
                        "start":4
                    }
                ],
                "end":15405,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF14",
                "start":14841,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":54.3,
                        "code":"PF05103",
                        "end":71,
                        "start":8
                    }
                ],
                "end":15841,
                "id":"gpsB",
                "start":15517,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":52.4,
                        "code":"PF02926",
                        "end":157,
                        "start":13
                    }
                ],
                "end":17054,
                "id":"rlmL_1",
                "start":16430,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":85.3,
                        "code":"PF01170",
                        "end":106,
                        "start":1
                    }
                ],
                "end":17563,
                "id":"rlmL_2",
                "start":17224,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":596.0,
                        "code":"PF02074",
                        "end":491,
                        "start":8
                    }
                ],
                "end":19075,
                "id":"ypwA",
                "start":17581,
                "strand":1
            },
            {
                "domains":[],
                "end":19810,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF19",
                "start":19279,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":82.1,
                        "code":"PF00195",
                        "end":207,
                        "start":56
                    }
                ],
                "end":21086,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF20",
                "start":20000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":88.3,
                        "code":"PF04140",
                        "end":162,
                        "start":70
                    }
                ],
                "end":21589,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF21",
                "start":21085,
                "strand":1
            },
            {
                "domains":[],
                "end":21991,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF22",
                "start":21688,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.2,
                        "code":"PF00075",
                        "end":124,
                        "start":1
                    }
                ],
                "end":22374,
                "id":"rnhA",
                "start":21987,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":872.7,
                        "code":"PF01268",
                        "end":556,
                        "start":2
                    }
                ],
                "end":24264,
                "id":"fhs1",
                "start":22593,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":201.6,
                        "code":"PF01904",
                        "end":266,
                        "start":17
                    }
                ],
                "end":25135,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF25",
                "start":24280,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":36.5,
                        "code":"PF01966",
                        "end":125,
                        "start":26
                    }
                ],
                "end":25759,
                "id":"yedJ",
                "start":25144,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":406.0,
                        "code":"PF00303",
                        "end":318,
                        "start":5
                    }
                ],
                "end":26717,
                "id":"thyA",
                "start":25760,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":206.4,
                        "code":"PF00186",
                        "end":161,
                        "start":1
                    }
                ],
                "end":27232,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF28",
                "start":26737,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":77.6,
                        "code":"PF12804",
                        "end":142,
                        "start":1
                    }
                ],
                "end":27816,
                "id":"mobA",
                "start":27276,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":71.8,
                        "code":"PF02416",
                        "end":60,
                        "start":5
                    }
                ],
                "end":28109,
                "id":"tatAd_1",
                "start":27908,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":65.7,
                        "code":"PF02416",
                        "end":60,
                        "start":5
                    }
                ],
                "end":28322,
                "id":"tatAd_2",
                "start":28133,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":175.3,
                        "code":"PF00902",
                        "end":221,
                        "start":17
                    }
                ],
                "end":29153,
                "id":"tatC1_1",
                "start":28391,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":87.6,
                        "code":"PF06855",
                        "end":69,
                        "start":3
                    }
                ],
                "end":29448,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF33",
                "start":29229,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":59.0,
                        "code":"PF00149",
                        "end":219,
                        "start":1
                    },
                    {
                        "bitscore":52.7,
                        "code":"PF12320",
                        "end":357,
                        "start":266
                    }
                ],
                "end":30695,
                "id":"sbcD",
                "start":29543,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":74.9,
                        "code":"PF13476",
                        "end":312,
                        "start":5
                    },
                    {
                        "bitscore":46.4,
                        "code":"PF13558",
                        "end":997,
                        "start":914
                    }
                ],
                "end":33813,
                "id":"smc_1",
                "start":30696,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":102.0,
                        "code":"PF10763",
                        "end":82,
                        "start":1
                    }
                ],
                "end":34079,
                "id":"ytmB",
                "start":33830,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":86.1,
                        "code":"PF03167",
                        "end":212,
                        "start":49
                    }
                ],
                "end":34854,
                "id":"ung",
                "start":34176,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":68.3,
                        "code":"PF14181",
                        "end":170,
                        "start":14
                    },
                    {
                        "bitscore":194.5,
                        "code":"PF01625",
                        "end":358,
                        "start":206
                    },
                    {
                        "bitscore":163.9,
                        "code":"PF01641",
                        "end":501,
                        "start":381
                    }
                ],
                "end":36479,
                "id":"msrB",
                "start":34922,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":31.2,
                        "code":"PF00440",
                        "end":58,
                        "start":12
                    }
                ],
                "end":37136,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF39",
                "start":36563,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":44.5,
                        "code":"PF01738",
                        "end":196,
                        "start":54
                    }
                ],
                "end":37926,
                "id":"mhqD",
                "start":37311,
                "strand":1
            },
            {
                "domains":[],
                "end":38183,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF41",
                "start":37979,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":91.3,
                        "code":"PF00300",
                        "end":178,
                        "start":4
                    }
                ],
                "end":38939,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF42",
                "start":38393,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":34.1,
                        "code":"PF00037",
                        "end":25,
                        "start":2
                    }
                ],
                "end":39309,
                "id":"fdxA",
                "start":39162,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":206.2,
                        "code":"PF00106",
                        "end":202,
                        "start":7
                    }
                ],
                "end":40224,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region002_ORF44",
                "start":39483,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":87.3,
                        "code":"PF00708",
                        "end":89,
                        "start":4
                    }
                ],
                "end":40537,
                "id":"acyP",
                "start":40261,
                "strand":-1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
