var bs_data=[
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":20837,
        "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region003",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":55.6,
                        "code":"PF13040",
                        "end":39,
                        "start":1
                    }
                ],
                "end":315,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region003_ORF1",
                "start":168,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":239.0,
                        "code":"PF00155",
                        "end":376,
                        "start":28
                    }
                ],
                "end":1569,
                "id":"dapX_1",
                "start":420,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":62.9,
                        "code":"PF00717",
                        "end":106,
                        "start":35
                    }
                ],
                "end":2218,
                "id":"sipT",
                "start":1696,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":90.7,
                        "code":"PF11148",
                        "end":68,
                        "start":2
                    }
                ],
                "end":2654,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region003_ORF4",
                "start":2441,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":65.4,
                        "code":"PF07872",
                        "end":51,
                        "start":7
                    }
                ],
                "end":2913,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region003_ORF5",
                "start":2688,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":41.7,
                        "code":"PF07681",
                        "end":117,
                        "start":14
                    }
                ],
                "end":4145,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region003_ORF6",
                "start":3647,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":93.9,
                        "code":"PF00990",
                        "end":470,
                        "start":391
                    },
                    {
                        "bitscore":52.0,
                        "code":"PF08447",
                        "end":373,
                        "start":288
                    },
                    {
                        "bitscore":41.8,
                        "code":"PF13426",
                        "end":253,
                        "start":151
                    }
                ],
                "end":5847,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region003_ORF7",
                "start":4434,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":144.6,
                        "code":"PF04240",
                        "end":241,
                        "start":32
                    }
                ],
                "end":6751,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region003_ORF8",
                "start":5986,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":49.0,
                        "code":"PF01553",
                        "end":158,
                        "start":23
                    }
                ],
                "end":7400,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region003_ORF9",
                "start":6737,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":61.8,
                        "code":"PF13641",
                        "end":267,
                        "start":36
                    }
                ],
                "end":8520,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region003_ORF10",
                "start":7413,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":118.7,
                        "code":"PF01593",
                        "end":483,
                        "start":10
                    }
                ],
                "end":9989,
                "id":"crtNb_1",
                "start":8516,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":217.4,
                        "code":"PF00494",
                        "end":269,
                        "start":15
                    }
                ],
                "end":10837,
                "id":"yisP",
                "start":10000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":93.8,
                        "code":"PF01593",
                        "end":474,
                        "start":13
                    }
                ],
                "end":12321,
                "id":"crtNc",
                "start":10839,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":74.6,
                        "code":"PF01593",
                        "end":485,
                        "start":12
                    }
                ],
                "end":13802,
                "id":"crtN_1",
                "start":12317,
                "strand":-1
            },
            {
                "domains":[],
                "end":14203,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region003_ORF15",
                "start":14002,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":42.9,
                        "code":"PF09680",
                        "end":49,
                        "start":28
                    }
                ],
                "end":14434,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region003_ORF16",
                "start":14281,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":218.2,
                        "code":"PF02386",
                        "end":443,
                        "start":22
                    }
                ],
                "end":15846,
                "id":"ktrB_1",
                "start":14484,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":161.7,
                        "code":"PF14183",
                        "end":135,
                        "start":2
                    }
                ],
                "end":16312,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region003_ORF18",
                "start":15886,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":177.7,
                        "code":"PF02386",
                        "end":446,
                        "start":4
                    }
                ],
                "end":17881,
                "id":"ktrB_2",
                "start":16513,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":126.6,
                        "code":"PF06463",
                        "end":317,
                        "start":189
                    },
                    {
                        "bitscore":111.3,
                        "code":"PF04055",
                        "end":184,
                        "start":18
                    }
                ],
                "end":19198,
                "id":"moaA",
                "start":18187,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":57.5,
                        "code":"PF03454",
                        "end":411,
                        "start":340
                    },
                    {
                        "bitscore":87.2,
                        "code":"PF00994",
                        "end":327,
                        "start":189
                    },
                    {
                        "bitscore":124.1,
                        "code":"PF03453",
                        "end":176,
                        "start":8
                    }
                ],
                "end":20493,
                "id":"moeA",
                "start":19218,
                "strand":-1
            },
            {
                "domains":[],
                "end":20739,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region003_ORF22",
                "start":20604,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":20837,
        "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region003",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":55.6,
                        "code":"PF13040",
                        "end":39,
                        "start":1
                    }
                ],
                "end":315,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region003_ORF1",
                "start":168,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":239.0,
                        "code":"PF00155",
                        "end":376,
                        "start":28
                    }
                ],
                "end":1569,
                "id":"dapX_1",
                "start":420,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":62.9,
                        "code":"PF00717",
                        "end":106,
                        "start":35
                    }
                ],
                "end":2218,
                "id":"sipT",
                "start":1696,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":90.7,
                        "code":"PF11148",
                        "end":68,
                        "start":2
                    }
                ],
                "end":2654,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region003_ORF4",
                "start":2441,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":65.4,
                        "code":"PF07872",
                        "end":51,
                        "start":7
                    }
                ],
                "end":2913,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region003_ORF5",
                "start":2688,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":41.7,
                        "code":"PF07681",
                        "end":117,
                        "start":14
                    }
                ],
                "end":4145,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region003_ORF6",
                "start":3647,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":93.9,
                        "code":"PF00990",
                        "end":470,
                        "start":391
                    },
                    {
                        "bitscore":52.0,
                        "code":"PF08447",
                        "end":373,
                        "start":288
                    },
                    {
                        "bitscore":41.8,
                        "code":"PF13426",
                        "end":253,
                        "start":151
                    }
                ],
                "end":5847,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region003_ORF7",
                "start":4434,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":144.6,
                        "code":"PF04240",
                        "end":241,
                        "start":32
                    }
                ],
                "end":6751,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region003_ORF8",
                "start":5986,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":49.0,
                        "code":"PF01553",
                        "end":158,
                        "start":23
                    }
                ],
                "end":7400,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region003_ORF9",
                "start":6737,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":61.8,
                        "code":"PF13641",
                        "end":267,
                        "start":36
                    }
                ],
                "end":8520,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region003_ORF10",
                "start":7413,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":118.7,
                        "code":"PF01593",
                        "end":483,
                        "start":10
                    }
                ],
                "end":9989,
                "id":"crtNb_1",
                "start":8516,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":217.4,
                        "code":"PF00494",
                        "end":269,
                        "start":15
                    }
                ],
                "end":10837,
                "id":"yisP",
                "start":10000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":93.8,
                        "code":"PF01593",
                        "end":474,
                        "start":13
                    }
                ],
                "end":12321,
                "id":"crtNc",
                "start":10839,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":74.6,
                        "code":"PF01593",
                        "end":485,
                        "start":12
                    }
                ],
                "end":13802,
                "id":"crtN_1",
                "start":12317,
                "strand":-1
            },
            {
                "domains":[],
                "end":14203,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region003_ORF15",
                "start":14002,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":42.9,
                        "code":"PF09680",
                        "end":49,
                        "start":28
                    }
                ],
                "end":14434,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region003_ORF16",
                "start":14281,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":218.2,
                        "code":"PF02386",
                        "end":443,
                        "start":22
                    }
                ],
                "end":15846,
                "id":"ktrB_1",
                "start":14484,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":161.7,
                        "code":"PF14183",
                        "end":135,
                        "start":2
                    }
                ],
                "end":16312,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region003_ORF18",
                "start":15886,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":177.7,
                        "code":"PF02386",
                        "end":446,
                        "start":4
                    }
                ],
                "end":17881,
                "id":"ktrB_2",
                "start":16513,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":126.6,
                        "code":"PF06463",
                        "end":317,
                        "start":189
                    },
                    {
                        "bitscore":111.3,
                        "code":"PF04055",
                        "end":184,
                        "start":18
                    }
                ],
                "end":19198,
                "id":"moaA",
                "start":18187,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":57.5,
                        "code":"PF03454",
                        "end":411,
                        "start":340
                    },
                    {
                        "bitscore":87.2,
                        "code":"PF00994",
                        "end":327,
                        "start":189
                    },
                    {
                        "bitscore":124.1,
                        "code":"PF03453",
                        "end":176,
                        "start":8
                    }
                ],
                "end":20493,
                "id":"moeA",
                "start":19218,
                "strand":-1
            },
            {
                "domains":[],
                "end":20739,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region003_ORF22",
                "start":20604,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":21881,
        "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region006",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":149.0,
                        "code":"PF02502",
                        "end":127,
                        "start":3
                    }
                ],
                "end":1047,
                "id":"ywlF_2",
                "start":630,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":157.4,
                        "code":"PF02734",
                        "end":208,
                        "start":32
                    }
                ],
                "end":1913,
                "id":"dhaL-2",
                "start":1256,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":397.9,
                        "code":"PF02733",
                        "end":330,
                        "start":17
                    }
                ],
                "end":2931,
                "id":"dhaK-2",
                "start":1926,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":56.5,
                        "code":"PF07690",
                        "end":275,
                        "start":18
                    }
                ],
                "end":4315,
                "id":"yoaB",
                "start":3022,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":73.2,
                        "code":"PF00107",
                        "end":112,
                        "start":1
                    }
                ],
                "end":4794,
                "id":"eltD_1",
                "start":4341,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":99.5,
                        "code":"PF08240",
                        "end":160,
                        "start":42
                    }
                ],
                "end":5449,
                "id":"eltD_2",
                "start":4753,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":52.9,
                        "code":"PF08220",
                        "end":48,
                        "start":1
                    },
                    {
                        "bitscore":162.2,
                        "code":"PF00455",
                        "end":220,
                        "start":60
                    }
                ],
                "end":6491,
                "id":"ydjF_2",
                "start":5759,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":221.4,
                        "code":"PF13561",
                        "end":253,
                        "start":21
                    }
                ],
                "end":7329,
                "id":"golD",
                "start":6561,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":31.0,
                        "code":"PF08279",
                        "end":220,
                        "start":161
                    },
                    {
                        "bitscore":103.8,
                        "code":"PF00072",
                        "end":116,
                        "start":4
                    }
                ],
                "end":8071,
                "id":"dcuR",
                "start":7369,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":58.3,
                        "code":"PF02518",
                        "end":529,
                        "start":422
                    },
                    {
                        "bitscore":33.1,
                        "code":"PF14689",
                        "end":381,
                        "start":320
                    },
                    {
                        "bitscore":35.0,
                        "code":"PF00989",
                        "end":315,
                        "start":213
                    },
                    {
                        "bitscore":102.9,
                        "code":"PF17203",
                        "end":172,
                        "start":34
                    }
                ],
                "end":9672,
                "id":"dcuS",
                "start":8067,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":237.0,
                        "code":"PF13249",
                        "end":295,
                        "start":10
                    },
                    {
                        "bitscore":285.8,
                        "code":"PF13243",
                        "end":623,
                        "start":305
                    }
                ],
                "end":11881,
                "id":"sqhC",
                "start":10000,
                "strand":1
            },
            {
                "domains":[],
                "end":12582,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region006_ORF12",
                "start":12015,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":157.3,
                        "code":"PF13460",
                        "end":193,
                        "start":7
                    }
                ],
                "end":13543,
                "id":"yhfK_2",
                "start":12892,
                "strand":-1
            },
            {
                "domains":[],
                "end":13960,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region006_ORF14",
                "start":13696,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":151.8,
                        "code":"PF00248",
                        "end":264,
                        "start":18
                    }
                ],
                "end":15167,
                "id":"dkgB",
                "start":14324,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":48.8,
                        "code":"PF00274",
                        "end":223,
                        "start":4
                    }
                ],
                "end":16351,
                "id":"fda",
                "start":15460,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":77.1,
                        "code":"PF01261",
                        "end":234,
                        "start":17
                    }
                ],
                "end":17223,
                "id":"nfo_2",
                "start":16383,
                "strand":-1
            },
            {
                "domains":[],
                "end":19199,
                "id":"smc_4",
                "start":17384,
                "strand":-1
            },
            {
                "domains":[],
                "end":19469,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region006_ORF19",
                "start":19205,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":60.0,
                        "code":"PF03176",
                        "end":586,
                        "start":365
                    },
                    {
                        "bitscore":81.2,
                        "code":"PF03176",
                        "end":334,
                        "start":26
                    }
                ],
                "end":21216,
                "id":"ydfJ",
                "start":19446,
                "strand":-1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
