var bs_data=[
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":29059,
        "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region002",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":46.0,
                        "code":"PF01476",
                        "end":69,
                        "start":27
                    },
                    {
                        "bitscore":45.3,
                        "code":"PF01476",
                        "end":121,
                        "start":79
                    },
                    {
                        "bitscore":67.7,
                        "code":"PF06725",
                        "end":277,
                        "start":216
                    }
                ],
                "end":1245,
                "id":"yocH_1",
                "start":408,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.6,
                        "code":"PF00485",
                        "end":153,
                        "start":40
                    }
                ],
                "end":1942,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region002_ORF2",
                "start":1402,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":89.0,
                        "code":"PF02334",
                        "end":125,
                        "start":9
                    }
                ],
                "end":2442,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region002_ORF3",
                "start":2061,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":118.0,
                        "code":"PF00296",
                        "end":303,
                        "start":1
                    }
                ],
                "end":3474,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region002_ORF4",
                "start":2469,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":46.6,
                        "code":"PF13509",
                        "end":65,
                        "start":6
                    },
                    {
                        "bitscore":81.6,
                        "code":"PF17783",
                        "end":284,
                        "start":227
                    }
                ],
                "end":4360,
                "id":"cvfB",
                "start":3493,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":134.2,
                        "code":"PF07690",
                        "end":312,
                        "start":18
                    }
                ],
                "end":5723,
                "id":"ymfD",
                "start":4481,
                "strand":1
            },
            {
                "domains":[],
                "end":6299,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region002_ORF7",
                "start":5741,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":107.9,
                        "code":"PF00534",
                        "end":346,
                        "start":185
                    },
                    {
                        "bitscore":88.7,
                        "code":"PF13439",
                        "end":178,
                        "start":14
                    }
                ],
                "end":8514,
                "id":"mgtA",
                "start":7344,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":83.9,
                        "code":"PF01370",
                        "end":291,
                        "start":3
                    }
                ],
                "end":9676,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region002_ORF9",
                "start":8527,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":51.0,
                        "code":"PF16177",
                        "end":89,
                        "start":32
                    },
                    {
                        "bitscore":263.3,
                        "code":"PF00501",
                        "end":526,
                        "start":91
                    },
                    {
                        "bitscore":82.2,
                        "code":"PF13193",
                        "end":612,
                        "start":534
                    }
                ],
                "end":11962,
                "id":"acs_1",
                "start":10000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":544.6,
                        "code":"PF01039",
                        "end":505,
                        "start":23
                    }
                ],
                "end":14096,
                "id":"accD5",
                "start":12572,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":219.6,
                        "code":"PF00378",
                        "end":258,
                        "start":9
                    }
                ],
                "end":14889,
                "id":"crt",
                "start":14112,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":168.7,
                        "code":"PF00682",
                        "end":281,
                        "start":8
                    }
                ],
                "end":15809,
                "id":"yngG_1",
                "start":14888,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":61.5,
                        "code":"PF00364",
                        "end":69,
                        "start":2
                    }
                ],
                "end":16036,
                "id":"yngHB",
                "start":15823,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":118.3,
                        "code":"PF02785",
                        "end":442,
                        "start":336
                    },
                    {
                        "bitscore":270.2,
                        "code":"PF02786",
                        "end":324,
                        "start":115
                    },
                    {
                        "bitscore":154.1,
                        "code":"PF00289",
                        "end":110,
                        "start":1
                    }
                ],
                "end":17404,
                "id":"accC_2",
                "start":16048,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":66.0,
                        "code":"PF13193",
                        "end":528,
                        "start":453
                    },
                    {
                        "bitscore":357.2,
                        "code":"PF00501",
                        "end":445,
                        "start":12
                    }
                ],
                "end":19059,
                "id":"fadD3",
                "start":17418,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":173.5,
                        "code":"PF00441",
                        "end":379,
                        "start":230
                    },
                    {
                        "bitscore":90.9,
                        "code":"PF02770",
                        "end":218,
                        "start":122
                    },
                    {
                        "bitscore":125.6,
                        "code":"PF02771",
                        "end":118,
                        "start":6
                    }
                ],
                "end":20220,
                "id":"bcd",
                "start":19077,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":113.8,
                        "code":"PF17932",
                        "end":187,
                        "start":73
                    },
                    {
                        "bitscore":55.8,
                        "code":"PF00440",
                        "end":54,
                        "start":8
                    }
                ],
                "end":20918,
                "id":"kstR2_1",
                "start":20285,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":29.2,
                        "code":"PF03989",
                        "end":755,
                        "start":706
                    },
                    {
                        "bitscore":30.5,
                        "code":"PF03989",
                        "end":701,
                        "start":654
                    },
                    {
                        "bitscore":28.8,
                        "code":"PF03989",
                        "end":651,
                        "start":605
                    },
                    {
                        "bitscore":22.7,
                        "code":"PF03989",
                        "end":599,
                        "start":549
                    },
                    {
                        "bitscore":12.8,
                        "code":"PF03989",
                        "end":543,
                        "start":504
                    },
                    {
                        "bitscore":492.5,
                        "code":"PF00521",
                        "end":471,
                        "start":31
                    }
                ],
                "end":23496,
                "id":"parC",
                "start":21045,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":106.2,
                        "code":"PF00986",
                        "end":629,
                        "start":567
                    },
                    {
                        "bitscore":62.7,
                        "code":"PF01751",
                        "end":534,
                        "start":423
                    },
                    {
                        "bitscore":192.9,
                        "code":"PF00204",
                        "end":393,
                        "start":222
                    },
                    {
                        "bitscore":70.5,
                        "code":"PF02518",
                        "end":177,
                        "start":33
                    }
                ],
                "end":25464,
                "id":"parE",
                "start":23511,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":119.8,
                        "code":"PF13380",
                        "end":133,
                        "start":18
                    }
                ],
                "end":26065,
                "id":"yccU",
                "start":25654,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":201.5,
                        "code":"PF04069",
                        "end":502,
                        "start":237
                    },
                    {
                        "bitscore":76.9,
                        "code":"PF00528",
                        "end":209,
                        "start":37
                    }
                ],
                "end":27604,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region002_ORF22",
                "start":26077,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":124.0,
                        "code":"PF00005",
                        "end":165,
                        "start":18
                    }
                ],
                "end":28668,
                "id":"btuD_1",
                "start":27600,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":20459,
        "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region004",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":74.1,
                        "code":"PF00535",
                        "end":260,
                        "start":57
                    }
                ],
                "end":2105,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region004_ORF1",
                "start":707,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":127.3,
                        "code":"PF01522",
                        "end":242,
                        "start":118
                    },
                    {
                        "bitscore":46.0,
                        "code":"PF01476",
                        "end":69,
                        "start":28
                    }
                ],
                "end":3261,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region004_ORF2",
                "start":2295,
                "strand":-1
            },
            {
                "domains":[],
                "end":4503,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region004_ORF3",
                "start":4023,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":47.3,
                        "code":"PF07875",
                        "end":126,
                        "start":80
                    }
                ],
                "end":5040,
                "id":"cotF",
                "start":4659,
                "strand":1
            },
            {
                "domains":[],
                "end":6372,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region004_ORF5",
                "start":5976,
                "strand":-1
            },
            {
                "domains":[],
                "end":6817,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region004_ORF6",
                "start":6562,
                "strand":-1
            },
            {
                "domains":[],
                "end":7164,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region004_ORF7",
                "start":6981,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":90.1,
                        "code":"PF00589",
                        "end":235,
                        "start":43
                    }
                ],
                "end":8381,
                "id":"xerC_2",
                "start":7583,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":148.1,
                        "code":"PF00756",
                        "end":238,
                        "start":14
                    }
                ],
                "end":9498,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region004_ORF9",
                "start":8766,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":98.4,
                        "code":"PF13563",
                        "end":158,
                        "start":9
                    }
                ],
                "end":10026,
                "id":"yjcG",
                "start":9513,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":62.9,
                        "code":"PF13673",
                        "end":152,
                        "start":16
                    }
                ],
                "end":10459,
                "id":"yjcF",
                "start":10000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":107.0,
                        "code":"PF04239",
                        "end":204,
                        "start":87
                    }
                ],
                "end":11246,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region004_ORF12",
                "start":10556,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":73.2,
                        "code":"PF00753",
                        "end":205,
                        "start":12
                    }
                ],
                "end":12121,
                "id":"gloB_2",
                "start":11224,
                "strand":-1
            },
            {
                "domains":[],
                "end":12436,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region004_ORF14",
                "start":12139,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":72.7,
                        "code":"PF07098",
                        "end":99,
                        "start":9
                    }
                ],
                "end":12798,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region004_ORF15",
                "start":12480,
                "strand":-1
            },
            {
                "domains":[],
                "end":13155,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region004_ORF16",
                "start":12858,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":156.3,
                        "code":"PF10612",
                        "end":145,
                        "start":1
                    }
                ],
                "end":13800,
                "id":"cotY",
                "start":13347,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":97.8,
                        "code":"PF14153",
                        "end":162,
                        "start":44
                    }
                ],
                "end":14329,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region004_ORF18",
                "start":13840,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":276.3,
                        "code":"PF13561",
                        "end":255,
                        "start":15
                    }
                ],
                "end":15386,
                "id":"fabI",
                "start":14606,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":111.1,
                        "code":"PF01769",
                        "end":444,
                        "start":322
                    },
                    {
                        "bitscore":40.0,
                        "code":"PF00571",
                        "end":258,
                        "start":202
                    },
                    {
                        "bitscore":40.4,
                        "code":"PF00571",
                        "end":196,
                        "start":138
                    },
                    {
                        "bitscore":91.3,
                        "code":"PF03448",
                        "end":136,
                        "start":35
                    }
                ],
                "end":16845,
                "id":"mgtE",
                "start":15480,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":50.2,
                        "code":"PF00149",
                        "end":197,
                        "start":1
                    }
                ],
                "end":17845,
                "id":"prpE",
                "start":17113,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":98.2,
                        "code":"PF00849",
                        "end":224,
                        "start":72
                    }
                ],
                "end":18772,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000001.region004_ORF22",
                "start":17935,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":93.2,
                        "code":"PF01513",
                        "end":237,
                        "start":4
                    }
                ],
                "end":19619,
                "id":"ppnKA",
                "start":18812,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":131.4,
                        "code":"PF04607",
                        "end":162,
                        "start":42
                    }
                ],
                "end":20256,
                "id":"yjbM",
                "start":19623,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":10390,
        "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000003.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":50.3,
                        "code":"PF02302",
                        "end":485,
                        "start":401
                    },
                    {
                        "bitscore":52.4,
                        "code":"PF02378",
                        "end":282,
                        "start":21
                    }
                ],
                "end":2587,
                "id":"mtlA_1",
                "start":1114,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":56.6,
                        "code":"PF00583",
                        "end":136,
                        "start":26
                    }
                ],
                "end":3630,
                "id":"ectA",
                "start":3111,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":265.4,
                        "code":"PF00202",
                        "end":414,
                        "start":16
                    }
                ],
                "end":4957,
                "id":"ectB",
                "start":3676,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":208.1,
                        "code":"PF06339",
                        "end":127,
                        "start":1
                    }
                ],
                "end":5390,
                "id":"ectC",
                "start":5000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":49.4,
                        "code":"PF00903",
                        "end":119,
                        "start":4
                    }
                ],
                "end":5929,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000003.region001_ORF5",
                "start":5503,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":91.6,
                        "code":"PF14140",
                        "end":42,
                        "start":1
                    }
                ],
                "end":6263,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000003.region001_ORF6",
                "start":6134,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":132.7,
                        "code":"PF01902",
                        "end":221,
                        "start":1
                    }
                ],
                "end":7192,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000003.region001_ORF7",
                "start":6526,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":140.1,
                        "code":"PF01758",
                        "end":221,
                        "start":41
                    }
                ],
                "end":9082,
                "id":"panS_1",
                "start":8092,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":15418,
        "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000004.region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":742.2,
                        "code":"PF00920",
                        "end":557,
                        "start":39
                    }
                ],
                "end":1803,
                "id":"ilvD",
                "start":108,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":313.8,
                        "code":"PF00202",
                        "end":443,
                        "start":22
                    }
                ],
                "end":3472,
                "id":"dat_2",
                "start":2110,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":192.7,
                        "code":"PF00282",
                        "end":436,
                        "start":63
                    }
                ],
                "end":5004,
                "id":"ddc",
                "start":3468,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":187.5,
                        "code":"PF04183",
                        "end":375,
                        "start":140
                    },
                    {
                        "bitscore":119.8,
                        "code":"PF06276",
                        "end":563,
                        "start":405
                    }
                ],
                "end":6764,
                "id":"iucA",
                "start":5000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":163.9,
                        "code":"PF13523",
                        "end":164,
                        "start":20
                    }
                ],
                "end":7326,
                "id":"aacA4",
                "start":6753,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":392.3,
                        "code":"PF13434",
                        "end":342,
                        "start":4
                    }
                ],
                "end":8635,
                "id":"iucD_3",
                "start":7306,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":246.1,
                        "code":"PF04183",
                        "end":393,
                        "start":143
                    },
                    {
                        "bitscore":138.4,
                        "code":"PF06276",
                        "end":577,
                        "start":414
                    }
                ],
                "end":10418,
                "id":"iucC",
                "start":8621,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":155.4,
                        "code":"PF00300",
                        "end":185,
                        "start":3
                    }
                ],
                "end":11058,
                "id":"pspA",
                "start":10485,
                "strand":1
            },
            {
                "domains":[],
                "end":11377,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000004.region001_ORF9",
                "start":11251,
                "strand":1
            },
            {
                "domains":[],
                "end":11578,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000004.region001_ORF10",
                "start":11449,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":192.8,
                        "code":"PF00463",
                        "end":248,
                        "start":5
                    },
                    {
                        "bitscore":166.3,
                        "code":"PF00463",
                        "end":423,
                        "start":246
                    }
                ],
                "end":13177,
                "id":"aceA",
                "start":11884,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":286.8,
                        "code":"PF11794",
                        "end":270,
                        "start":5
                    },
                    {
                        "bitscore":214.7,
                        "code":"PF03241",
                        "end":476,
                        "start":277
                    }
                ],
                "end":14729,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000004.region001_ORF12",
                "start":13286,
                "strand":1
            },
            {
                "domains":[],
                "end":14881,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000004.region001_ORF13",
                "start":14743,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":70.3,
                        "code":"PF13217",
                        "end":50,
                        "start":1
                    }
                ],
                "end":15377,
                "id":"Halobacillus_andaensis_GCF_014636475.prokka-NZ_BMEL01000004.region001_ORF14",
                "start":15164,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":29059,
        "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region002",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":46.0,
                        "code":"PF01476",
                        "end":69,
                        "start":27
                    },
                    {
                        "bitscore":45.3,
                        "code":"PF01476",
                        "end":121,
                        "start":79
                    },
                    {
                        "bitscore":67.7,
                        "code":"PF06725",
                        "end":277,
                        "start":216
                    }
                ],
                "end":1245,
                "id":"yocH_1",
                "start":408,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":27.6,
                        "code":"PF00485",
                        "end":153,
                        "start":40
                    }
                ],
                "end":1942,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region002_ORF2",
                "start":1402,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":89.0,
                        "code":"PF02334",
                        "end":125,
                        "start":9
                    }
                ],
                "end":2442,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region002_ORF3",
                "start":2061,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":118.0,
                        "code":"PF00296",
                        "end":303,
                        "start":1
                    }
                ],
                "end":3474,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region002_ORF4",
                "start":2469,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":46.6,
                        "code":"PF13509",
                        "end":65,
                        "start":6
                    },
                    {
                        "bitscore":81.6,
                        "code":"PF17783",
                        "end":284,
                        "start":227
                    }
                ],
                "end":4360,
                "id":"cvfB",
                "start":3493,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":134.2,
                        "code":"PF07690",
                        "end":312,
                        "start":18
                    }
                ],
                "end":5723,
                "id":"ymfD",
                "start":4481,
                "strand":1
            },
            {
                "domains":[],
                "end":6299,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region002_ORF7",
                "start":5741,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":107.9,
                        "code":"PF00534",
                        "end":346,
                        "start":185
                    },
                    {
                        "bitscore":88.7,
                        "code":"PF13439",
                        "end":178,
                        "start":14
                    }
                ],
                "end":8514,
                "id":"mgtA",
                "start":7344,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":83.9,
                        "code":"PF01370",
                        "end":291,
                        "start":3
                    }
                ],
                "end":9676,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region002_ORF9",
                "start":8527,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":51.0,
                        "code":"PF16177",
                        "end":89,
                        "start":32
                    },
                    {
                        "bitscore":263.3,
                        "code":"PF00501",
                        "end":526,
                        "start":91
                    },
                    {
                        "bitscore":82.2,
                        "code":"PF13193",
                        "end":612,
                        "start":534
                    }
                ],
                "end":11962,
                "id":"acs_1",
                "start":10000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":544.6,
                        "code":"PF01039",
                        "end":505,
                        "start":23
                    }
                ],
                "end":14096,
                "id":"accD5",
                "start":12572,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":219.6,
                        "code":"PF00378",
                        "end":258,
                        "start":9
                    }
                ],
                "end":14889,
                "id":"crt",
                "start":14112,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":168.7,
                        "code":"PF00682",
                        "end":281,
                        "start":8
                    }
                ],
                "end":15809,
                "id":"yngG_1",
                "start":14888,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":61.5,
                        "code":"PF00364",
                        "end":69,
                        "start":2
                    }
                ],
                "end":16036,
                "id":"yngHB",
                "start":15823,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":118.3,
                        "code":"PF02785",
                        "end":442,
                        "start":336
                    },
                    {
                        "bitscore":270.2,
                        "code":"PF02786",
                        "end":324,
                        "start":115
                    },
                    {
                        "bitscore":154.1,
                        "code":"PF00289",
                        "end":110,
                        "start":1
                    }
                ],
                "end":17404,
                "id":"accC_2",
                "start":16048,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":66.0,
                        "code":"PF13193",
                        "end":528,
                        "start":453
                    },
                    {
                        "bitscore":357.2,
                        "code":"PF00501",
                        "end":445,
                        "start":12
                    }
                ],
                "end":19059,
                "id":"fadD3",
                "start":17418,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":173.5,
                        "code":"PF00441",
                        "end":379,
                        "start":230
                    },
                    {
                        "bitscore":90.9,
                        "code":"PF02770",
                        "end":218,
                        "start":122
                    },
                    {
                        "bitscore":125.6,
                        "code":"PF02771",
                        "end":118,
                        "start":6
                    }
                ],
                "end":20220,
                "id":"bcd",
                "start":19077,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":113.8,
                        "code":"PF17932",
                        "end":187,
                        "start":73
                    },
                    {
                        "bitscore":55.8,
                        "code":"PF00440",
                        "end":54,
                        "start":8
                    }
                ],
                "end":20918,
                "id":"kstR2_1",
                "start":20285,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":29.2,
                        "code":"PF03989",
                        "end":755,
                        "start":706
                    },
                    {
                        "bitscore":30.5,
                        "code":"PF03989",
                        "end":701,
                        "start":654
                    },
                    {
                        "bitscore":28.8,
                        "code":"PF03989",
                        "end":651,
                        "start":605
                    },
                    {
                        "bitscore":22.7,
                        "code":"PF03989",
                        "end":599,
                        "start":549
                    },
                    {
                        "bitscore":12.8,
                        "code":"PF03989",
                        "end":543,
                        "start":504
                    },
                    {
                        "bitscore":492.5,
                        "code":"PF00521",
                        "end":471,
                        "start":31
                    }
                ],
                "end":23496,
                "id":"parC",
                "start":21045,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":106.2,
                        "code":"PF00986",
                        "end":629,
                        "start":567
                    },
                    {
                        "bitscore":62.7,
                        "code":"PF01751",
                        "end":534,
                        "start":423
                    },
                    {
                        "bitscore":192.9,
                        "code":"PF00204",
                        "end":393,
                        "start":222
                    },
                    {
                        "bitscore":70.5,
                        "code":"PF02518",
                        "end":177,
                        "start":33
                    }
                ],
                "end":25464,
                "id":"parE",
                "start":23511,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":119.8,
                        "code":"PF13380",
                        "end":133,
                        "start":18
                    }
                ],
                "end":26065,
                "id":"yccU",
                "start":25654,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":201.5,
                        "code":"PF04069",
                        "end":502,
                        "start":237
                    },
                    {
                        "bitscore":76.9,
                        "code":"PF00528",
                        "end":209,
                        "start":37
                    }
                ],
                "end":27604,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region002_ORF22",
                "start":26077,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":124.0,
                        "code":"PF00005",
                        "end":165,
                        "start":18
                    }
                ],
                "end":28668,
                "id":"btuD_1",
                "start":27600,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":20459,
        "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region004",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":74.1,
                        "code":"PF00535",
                        "end":260,
                        "start":57
                    }
                ],
                "end":2105,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region004_ORF1",
                "start":707,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":127.3,
                        "code":"PF01522",
                        "end":242,
                        "start":118
                    },
                    {
                        "bitscore":46.0,
                        "code":"PF01476",
                        "end":69,
                        "start":28
                    }
                ],
                "end":3261,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region004_ORF2",
                "start":2295,
                "strand":-1
            },
            {
                "domains":[],
                "end":4503,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region004_ORF3",
                "start":4023,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":47.3,
                        "code":"PF07875",
                        "end":126,
                        "start":80
                    }
                ],
                "end":5040,
                "id":"cotF",
                "start":4659,
                "strand":1
            },
            {
                "domains":[],
                "end":6372,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region004_ORF5",
                "start":5976,
                "strand":-1
            },
            {
                "domains":[],
                "end":6817,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region004_ORF6",
                "start":6562,
                "strand":-1
            },
            {
                "domains":[],
                "end":7164,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region004_ORF7",
                "start":6981,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":90.1,
                        "code":"PF00589",
                        "end":235,
                        "start":43
                    }
                ],
                "end":8381,
                "id":"xerC_2",
                "start":7583,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":148.1,
                        "code":"PF00756",
                        "end":238,
                        "start":14
                    }
                ],
                "end":9498,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region004_ORF9",
                "start":8766,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":98.4,
                        "code":"PF13563",
                        "end":158,
                        "start":9
                    }
                ],
                "end":10026,
                "id":"yjcG",
                "start":9513,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":62.9,
                        "code":"PF13673",
                        "end":152,
                        "start":16
                    }
                ],
                "end":10459,
                "id":"yjcF",
                "start":10000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":107.0,
                        "code":"PF04239",
                        "end":204,
                        "start":87
                    }
                ],
                "end":11246,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region004_ORF12",
                "start":10556,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":73.2,
                        "code":"PF00753",
                        "end":205,
                        "start":12
                    }
                ],
                "end":12121,
                "id":"gloB_2",
                "start":11224,
                "strand":-1
            },
            {
                "domains":[],
                "end":12436,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region004_ORF14",
                "start":12139,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":72.7,
                        "code":"PF07098",
                        "end":99,
                        "start":9
                    }
                ],
                "end":12798,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region004_ORF15",
                "start":12480,
                "strand":-1
            },
            {
                "domains":[],
                "end":13155,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region004_ORF16",
                "start":12858,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":156.3,
                        "code":"PF10612",
                        "end":145,
                        "start":1
                    }
                ],
                "end":13800,
                "id":"cotY",
                "start":13347,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":97.8,
                        "code":"PF14153",
                        "end":162,
                        "start":44
                    }
                ],
                "end":14329,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region004_ORF18",
                "start":13840,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":276.3,
                        "code":"PF13561",
                        "end":255,
                        "start":15
                    }
                ],
                "end":15386,
                "id":"fabI",
                "start":14606,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":111.1,
                        "code":"PF01769",
                        "end":444,
                        "start":322
                    },
                    {
                        "bitscore":40.0,
                        "code":"PF00571",
                        "end":258,
                        "start":202
                    },
                    {
                        "bitscore":40.4,
                        "code":"PF00571",
                        "end":196,
                        "start":138
                    },
                    {
                        "bitscore":91.3,
                        "code":"PF03448",
                        "end":136,
                        "start":35
                    }
                ],
                "end":16845,
                "id":"mgtE",
                "start":15480,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":50.2,
                        "code":"PF00149",
                        "end":197,
                        "start":1
                    }
                ],
                "end":17845,
                "id":"prpE",
                "start":17113,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":98.2,
                        "code":"PF00849",
                        "end":224,
                        "start":72
                    }
                ],
                "end":18772,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00001_NZ_JAGG...region004_ORF22",
                "start":17935,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":93.2,
                        "code":"PF01513",
                        "end":237,
                        "start":4
                    }
                ],
                "end":19619,
                "id":"ppnKA",
                "start":18812,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":131.4,
                        "code":"PF04607",
                        "end":162,
                        "start":42
                    }
                ],
                "end":20256,
                "id":"yjbM",
                "start":19623,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":15418,
        "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00003_NZ_JAGG...region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":742.2,
                        "code":"PF00920",
                        "end":557,
                        "start":39
                    }
                ],
                "end":1803,
                "id":"ilvD",
                "start":108,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":313.8,
                        "code":"PF00202",
                        "end":443,
                        "start":22
                    }
                ],
                "end":3472,
                "id":"dat_2",
                "start":2110,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":192.7,
                        "code":"PF00282",
                        "end":436,
                        "start":63
                    }
                ],
                "end":5004,
                "id":"ddc",
                "start":3468,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":187.5,
                        "code":"PF04183",
                        "end":375,
                        "start":140
                    },
                    {
                        "bitscore":119.8,
                        "code":"PF06276",
                        "end":563,
                        "start":405
                    }
                ],
                "end":6764,
                "id":"iucA",
                "start":5000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":163.9,
                        "code":"PF13523",
                        "end":164,
                        "start":20
                    }
                ],
                "end":7326,
                "id":"aacA4",
                "start":6753,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":392.3,
                        "code":"PF13434",
                        "end":342,
                        "start":4
                    }
                ],
                "end":8635,
                "id":"iucD_3",
                "start":7306,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":246.1,
                        "code":"PF04183",
                        "end":393,
                        "start":143
                    },
                    {
                        "bitscore":138.4,
                        "code":"PF06276",
                        "end":577,
                        "start":414
                    }
                ],
                "end":10418,
                "id":"iucC",
                "start":8621,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":155.4,
                        "code":"PF00300",
                        "end":185,
                        "start":3
                    }
                ],
                "end":11058,
                "id":"pspA",
                "start":10485,
                "strand":1
            },
            {
                "domains":[],
                "end":11377,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00003_NZ_JAGG...region001_ORF9",
                "start":11251,
                "strand":1
            },
            {
                "domains":[],
                "end":11578,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00003_NZ_JAGG...region001_ORF10",
                "start":11449,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":192.8,
                        "code":"PF00463",
                        "end":248,
                        "start":5
                    },
                    {
                        "bitscore":166.3,
                        "code":"PF00463",
                        "end":423,
                        "start":246
                    }
                ],
                "end":13177,
                "id":"aceA",
                "start":11884,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":286.8,
                        "code":"PF11794",
                        "end":270,
                        "start":5
                    },
                    {
                        "bitscore":214.7,
                        "code":"PF03241",
                        "end":476,
                        "start":277
                    }
                ],
                "end":14729,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00003_NZ_JAGG...region001_ORF12",
                "start":13286,
                "strand":1
            },
            {
                "domains":[],
                "end":14881,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00003_NZ_JAGG...region001_ORF13",
                "start":14743,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":70.3,
                        "code":"PF13217",
                        "end":50,
                        "start":1
                    }
                ],
                "end":15377,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00003_NZ_JAGG...region001_ORF14",
                "start":15164,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":10390,
        "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00004_NZ_JAGG...region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":140.1,
                        "code":"PF01758",
                        "end":221,
                        "start":41
                    }
                ],
                "end":2298,
                "id":"panS_2",
                "start":1308,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":132.7,
                        "code":"PF01902",
                        "end":221,
                        "start":1
                    }
                ],
                "end":3864,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00004_NZ_JAGG...region001_ORF2",
                "start":3198,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":91.6,
                        "code":"PF14140",
                        "end":42,
                        "start":1
                    }
                ],
                "end":4256,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00004_NZ_JAGG...region001_ORF3",
                "start":4127,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":49.4,
                        "code":"PF00903",
                        "end":119,
                        "start":4
                    }
                ],
                "end":4887,
                "id":"Halobacillus_andaensis_GCF_017874135.prokka-c00004_NZ_JAGG...region001_ORF4",
                "start":4461,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":208.1,
                        "code":"PF06339",
                        "end":127,
                        "start":1
                    }
                ],
                "end":5390,
                "id":"ectC",
                "start":5000,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":265.4,
                        "code":"PF00202",
                        "end":414,
                        "start":16
                    }
                ],
                "end":6714,
                "id":"ectB",
                "start":5433,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":56.6,
                        "code":"PF00583",
                        "end":136,
                        "start":26
                    }
                ],
                "end":7279,
                "id":"ectA",
                "start":6760,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":52.4,
                        "code":"PF02378",
                        "end":282,
                        "start":21
                    },
                    {
                        "bitscore":50.3,
                        "code":"PF02302",
                        "end":485,
                        "start":401
                    }
                ],
                "end":9276,
                "id":"mtlA_1",
                "start":7803,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":15415,
        "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region001",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":741.5,
                        "code":"PF00920",
                        "end":557,
                        "start":39
                    }
                ],
                "end":1812,
                "id":"ilvD_2",
                "start":117,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":103.3,
                        "code":"PF00202",
                        "end":201,
                        "start":21
                    }
                ],
                "end":2721,
                "id":"dat_2",
                "start":2112,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":202.8,
                        "code":"PF00202",
                        "end":238,
                        "start":11
                    }
                ],
                "end":3472,
                "id":"dat_3",
                "start":2725,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":197.9,
                        "code":"PF00282",
                        "end":436,
                        "start":59
                    }
                ],
                "end":5004,
                "id":"ddc",
                "start":3468,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":186.0,
                        "code":"PF04183",
                        "end":373,
                        "start":138
                    },
                    {
                        "bitscore":118.7,
                        "code":"PF06276",
                        "end":561,
                        "start":403
                    }
                ],
                "end":6758,
                "id":"iucA",
                "start":5000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":157.9,
                        "code":"PF13523",
                        "end":164,
                        "start":20
                    }
                ],
                "end":7308,
                "id":"iucB",
                "start":6747,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":401.2,
                        "code":"PF13434",
                        "end":343,
                        "start":4
                    }
                ],
                "end":8632,
                "id":"iucD_3",
                "start":7300,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":243.2,
                        "code":"PF04183",
                        "end":393,
                        "start":143
                    },
                    {
                        "bitscore":141.8,
                        "code":"PF06276",
                        "end":577,
                        "start":414
                    }
                ],
                "end":10415,
                "id":"iucC",
                "start":8618,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":160.2,
                        "code":"PF00300",
                        "end":185,
                        "start":3
                    }
                ],
                "end":11051,
                "id":"pspB",
                "start":10478,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":250.0,
                        "code":"PF00248",
                        "end":310,
                        "start":16
                    }
                ],
                "end":12049,
                "id":"iolS_1",
                "start":11116,
                "strand":1
            },
            {
                "domains":[],
                "end":12497,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region001_ORF11",
                "start":12371,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":186.5,
                        "code":"PF00463",
                        "end":249,
                        "start":5
                    },
                    {
                        "bitscore":169.6,
                        "code":"PF00463",
                        "end":423,
                        "start":246
                    }
                ],
                "end":14200,
                "id":"aceA",
                "start":12907,
                "strand":1
            }
        ],
        "start":1
    },
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":28781,
        "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region003",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":69.6,
                        "code":"PF00005",
                        "end":140,
                        "start":7
                    }
                ],
                "end":693,
                "id":"ybiT_2",
                "start":57,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":44.2,
                        "code":"PF01476",
                        "end":69,
                        "start":27
                    },
                    {
                        "bitscore":50.5,
                        "code":"PF01476",
                        "end":120,
                        "start":78
                    },
                    {
                        "bitscore":69.2,
                        "code":"PF06725",
                        "end":282,
                        "start":221
                    }
                ],
                "end":1846,
                "id":"yocH_1",
                "start":994,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":74.0,
                        "code":"PF02334",
                        "end":114,
                        "start":9
                    }
                ],
                "end":3005,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region003_ORF3",
                "start":2660,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":121.5,
                        "code":"PF00296",
                        "end":303,
                        "start":1
                    }
                ],
                "end":4093,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region003_ORF4",
                "start":3073,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":50.2,
                        "code":"PF13509",
                        "end":65,
                        "start":5
                    },
                    {
                        "bitscore":82.1,
                        "code":"PF17783",
                        "end":282,
                        "start":226
                    }
                ],
                "end":4958,
                "id":"cvfB",
                "start":4085,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":170.4,
                        "code":"PF07690",
                        "end":367,
                        "start":18
                    }
                ],
                "end":6311,
                "id":"ymfD",
                "start":5069,
                "strand":1
            },
            {
                "domains":[],
                "end":6889,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region003_ORF7",
                "start":6331,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":68.1,
                        "code":"PF00534",
                        "end":305,
                        "start":186
                    },
                    {
                        "bitscore":94.0,
                        "code":"PF13439",
                        "end":178,
                        "start":14
                    }
                ],
                "end":8515,
                "id":"mgtA",
                "start":7567,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":83.7,
                        "code":"PF01370",
                        "end":291,
                        "start":3
                    }
                ],
                "end":9677,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region003_ORF10",
                "start":8528,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":53.5,
                        "code":"PF16177",
                        "end":89,
                        "start":32
                    },
                    {
                        "bitscore":270.5,
                        "code":"PF00501",
                        "end":526,
                        "start":92
                    },
                    {
                        "bitscore":50.9,
                        "code":"PF13193",
                        "end":604,
                        "start":534
                    }
                ],
                "end":11839,
                "id":"acs",
                "start":10000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":256.7,
                        "code":"PF01039",
                        "end":217,
                        "start":1
                    }
                ],
                "end":12955,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region003_ORF12",
                "start":12295,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":229.5,
                        "code":"PF01039",
                        "end":274,
                        "start":23
                    }
                ],
                "end":13819,
                "id":"accD5",
                "start":12985,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":216.3,
                        "code":"PF00378",
                        "end":258,
                        "start":8
                    }
                ],
                "end":14613,
                "id":"crt",
                "start":13836,
                "strand":-1
            },
            {
                "domains":[],
                "end":14849,
                "id":"yngG_2",
                "start":14615,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":100.3,
                        "code":"PF00682",
                        "end":210,
                        "start":7
                    }
                ],
                "end":15532,
                "id":"yngG_3",
                "start":14848,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":64.5,
                        "code":"PF00364",
                        "end":69,
                        "start":2
                    }
                ],
                "end":15759,
                "id":"yngHB",
                "start":15546,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":115.4,
                        "code":"PF02785",
                        "end":188,
                        "start":82
                    },
                    {
                        "bitscore":87.3,
                        "code":"PF02786",
                        "end":70,
                        "start":1
                    }
                ],
                "end":16365,
                "id":"accC_2",
                "start":15771,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":84.7,
                        "code":"PF02786",
                        "end":205,
                        "start":115
                    },
                    {
                        "bitscore":151.3,
                        "code":"PF00289",
                        "end":110,
                        "start":1
                    }
                ],
                "end":17129,
                "id":"cfiB",
                "start":16499,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":69.4,
                        "code":"PF13193",
                        "end":528,
                        "start":453
                    },
                    {
                        "bitscore":361.0,
                        "code":"PF00501",
                        "end":445,
                        "start":12
                    }
                ],
                "end":18781,
                "id":"fadD3",
                "start":17128,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":176.6,
                        "code":"PF00441",
                        "end":379,
                        "start":230
                    },
                    {
                        "bitscore":87.3,
                        "code":"PF02770",
                        "end":218,
                        "start":122
                    },
                    {
                        "bitscore":128.7,
                        "code":"PF02771",
                        "end":118,
                        "start":6
                    }
                ],
                "end":19943,
                "id":"bcd",
                "start":18800,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":112.6,
                        "code":"PF17932",
                        "end":187,
                        "start":73
                    },
                    {
                        "bitscore":54.2,
                        "code":"PF00440",
                        "end":54,
                        "start":8
                    }
                ],
                "end":20641,
                "id":"kstR2_2",
                "start":20008,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":29.7,
                        "code":"PF03989",
                        "end":83,
                        "start":34
                    },
                    {
                        "bitscore":15.4,
                        "code":"PF03989",
                        "end":28,
                        "start":3
                    }
                ],
                "end":21203,
                "id":"parC_1",
                "start":20768,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":14.2,
                        "code":"PF03989",
                        "end":640,
                        "start":605
                    },
                    {
                        "bitscore":24.8,
                        "code":"PF03989",
                        "end":599,
                        "start":549
                    },
                    {
                        "bitscore":14.3,
                        "code":"PF03989",
                        "end":542,
                        "start":504
                    },
                    {
                        "bitscore":496.6,
                        "code":"PF00521",
                        "end":471,
                        "start":31
                    }
                ],
                "end":23218,
                "id":"parC_2",
                "start":21271,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":111.4,
                        "code":"PF00986",
                        "end":71,
                        "start":9
                    }
                ],
                "end":23512,
                "id":"parE_1",
                "start":23233,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":64.9,
                        "code":"PF01751",
                        "end":535,
                        "start":423
                    },
                    {
                        "bitscore":194.7,
                        "code":"PF00204",
                        "end":393,
                        "start":222
                    },
                    {
                        "bitscore":71.7,
                        "code":"PF02518",
                        "end":177,
                        "start":33
                    }
                ],
                "end":25187,
                "id":"parE_2",
                "start":23519,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":125.0,
                        "code":"PF13380",
                        "end":133,
                        "start":18
                    }
                ],
                "end":25790,
                "id":"yccU",
                "start":25379,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":199.5,
                        "code":"PF04069",
                        "end":502,
                        "start":237
                    },
                    {
                        "bitscore":82.6,
                        "code":"PF00528",
                        "end":209,
                        "start":37
                    }
                ],
                "end":27329,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region003_ORF28",
                "start":25802,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":120.2,
                        "code":"PF00005",
                        "end":165,
                        "start":18
                    }
                ],
                "end":28396,
                "id":"btuD_3",
                "start":27325,
                "strand":-1
            }
        ],
        "start":1
    },
    {
        "desc":"Halobacillus andaensis strain strain",
        "end":10396,
        "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region004",
        "mibig":false,
        "orfs":[
            {
                "domains":[
                    {
                        "bitscore":48.4,
                        "code":"PF02302",
                        "end":485,
                        "start":401
                    },
                    {
                        "bitscore":57.3,
                        "code":"PF02378",
                        "end":282,
                        "start":21
                    }
                ],
                "end":2573,
                "id":"mtlA",
                "start":1100,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":59.4,
                        "code":"PF00583",
                        "end":136,
                        "start":26
                    }
                ],
                "end":3626,
                "id":"ectA",
                "start":3107,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":240.6,
                        "code":"PF00202",
                        "end":368,
                        "start":16
                    }
                ],
                "end":4803,
                "id":"ectB",
                "start":3678,
                "strand":1
            },
            {
                "domains":[],
                "end":4960,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region004_ORF4",
                "start":4816,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":208.4,
                        "code":"PF06339",
                        "end":127,
                        "start":1
                    }
                ],
                "end":5396,
                "id":"ectC",
                "start":5000,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":47.9,
                        "code":"PF00903",
                        "end":117,
                        "start":3
                    }
                ],
                "end":5926,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region004_ORF6",
                "start":5506,
                "strand":1
            },
            {
                "domains":[],
                "end":6024,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region004_ORF7",
                "start":5931,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":93.2,
                        "code":"PF14140",
                        "end":42,
                        "start":1
                    }
                ],
                "end":6260,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region004_ORF8",
                "start":6131,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":67.5,
                        "code":"PF14145",
                        "end":91,
                        "start":35
                    }
                ],
                "end":6856,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region004_ORF9",
                "start":6508,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":138.9,
                        "code":"PF14342",
                        "end":215,
                        "start":72
                    }
                ],
                "end":7517,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region004_ORF10",
                "start":6860,
                "strand":1
            },
            {
                "domains":[
                    {
                        "bitscore":136.7,
                        "code":"PF01902",
                        "end":220,
                        "start":1
                    }
                ],
                "end":8512,
                "id":"Halobacillus_andaensis_OCO35-Chr1.prokka-c00001_gnl_CIA...region004_ORF11",
                "start":7849,
                "strand":-1
            },
            {
                "domains":[
                    {
                        "bitscore":404.4,
                        "code":"PF05067",
                        "end":280,
                        "start":1
                    }
                ],
                "end":9960,
                "id":"ydbD_1",
                "start":9096,
                "strand":-1
            }
        ],
        "start":1
    }
];
dataLoaded('bs_data');
